basePath: /api/v1
definitions:
  api.ErrorResponse:
    properties:
      message:
        type: string
      requestId:
        type: string
      statusCode:
        type: integer
    type: object
  types.Review:
    properties:
      object_id:
        type: integer
      text:
        type: string
    type: object
info:
  contact:
    name: Dmitriy Titov
  title: Go Masterclass
  version: "1.0"
paths:
  /reviews:
    post:
      parameters:
      - description: Review
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.Review'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Add Review
      tags:
      - post
  /reviews/object/{id}:
    get:
      parameters:
      - description: Object ID
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.Review'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Get revies by object ID
      tags:
      - get
produces:
- application/json
swagger: "2.0"
